server:
  port: 15002

spring:
  data:
    mongodb:
      host: mongodb           # Name of the MongoDB container (as per docker-compose)
      port: 27017
      database: school_management_system
      username: admin
      password: password123
      authentication-database: admin
      auto-index-creation: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SPRING_MAIL_USERNAME}
#    password: ${SPRING_MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: askanburi@gmail.com
    password: mpmazxewvudidrbk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            debug: true

app:
  base-url: http://localhost:15002
  admin:
    email: tume50193@gmail.com
    name: System Administrator
    notifications:
      enabled: true


momo:
  api:
    url: https://sandbox.momodeveloper.mtn.com
    key: "SDSAFAD3"
  subscription:
    key: "fba6f18ef89e4e3a9646333890be51a6"
  user:
    id: "TumeAskandara"

orange:
  api:
    url: https://api.orange.com
  client:
    id: "4RAFDFEed4"
    secret: "fadsk4r"
  merchant:
    account: "dgksdf"
